spring.application.name=cadastroChamados
server.port=8081

spring.datasoource.url = jdbc:h2:mem:testdb;DB_CLOSE_DELAY = -1;DB_CLOSE_ON_EXIT = FALSE;
spring.datasurce.driver = org.h2.Driver
spring.datasource.username =sa
spring.datasource.password =sa

spring.jpa.hibernate.dll-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.datasource.generate-unique-name=false
